project:
  type: website

execute:
  freeze: auto

lang: fr

filters:
  - fontawesome

format:
  hebstr-template-html: default

website:
  title: "{{< var alisp >}}"
  site-url: https://hebstr.quarto.pub/alisp/
  description: "Site officiel de l'ALiSP"
  favicon: _img/sym-red-nobg.png
  navbar:
    pinned: true
    logo: _img/logo-navbar.png
    title: false
    right:
      - text: "Bureau"
        href: bureau/bureau.qmd
      - text: "Section"
        menu:
          - text: "exemple"
            href: internat/exemple.qmd
          - text: "Trombinoscope"
            href: internat/trombi.qmd
      - text: Actualités
        href: blog/index.qmd
      - text: Guide&nbsp;de&nbsp;l'interne
        href: guide/index.qmd
      - text: "Aide&nbsp;méthodologique"
        href: aide/aide.qmd
  sidebar:
    - id: guide
      style: "floating"
      contents: guide
  page-footer:
    left: |
      <span>
        {{< fa brands creative-commons >}}
        [{{< var year >}} ALiSP](https://tinyurl.com/38p26zwy)
      </span>
      <br>
      <span>
        {{< fa brands creative-commons >}}&nbsp;{{< fa brands creative-commons-by >}}
        [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)
      </span>
    center: |
      [{{< var links.mail.text >}}]({{< var links.mail.href >}})
      [{{< var links.insta.text >}}]({{< var links.insta.href >}})
      [{{< var links.twitter.text >}}]({{< var links.twitter.href >}})
      [{{< var links.facebook.text >}}]({{< var links.facebook.href >}})
      [{{< var links.linkedin.text >}}]({{< var links.linkedin.href >}})
      <br>
      {{< var alisp >}}
    right: |
      <span>
        Site conçu avec {{< iconify fa6-brands r-project title='R' >}} et
        [{{< iconify simple-icons quarto title='https://quarto.org/' >}}](https://quarto.org/)
      </span>
      <br>
      <span>[{{< var repo.text >}}]({{< var repo.href >}})</span>
