project:
  type: website
  resources:
    - admin/**

execute:
  freeze: auto

lang: fr

format:
  hebstr-template-html: default
  # hebstr-template-typst: default

website:
  title: "{{< var alisp >}}"
  site-url: https://alisp.fr/
  description: "Association Lilloise des Internes de Santé Publique"
  open-graph: true
  twitter-card: true
  favicon: _resources/images/sym.svg
  navbar:
    pinned: false
    logo: _resources/images/logo-navbar.svg
    title: false
    right:
      - text: "bureau"
        href: bureau.qmd
      - text: actualités
        href: blog.qmd
      - text: guide&nbsp;du&nbsp;néo-interne
        href: guide.qmd
      - text: "aide&nbsp;méthodologique"
        href: formulaire.qmd
      - text: "{{< iconify fa6-solid rss title='Flux RSS' >}}"
        href: blog.xml
        aria-label: Flux RSS
  sidebar:
    - id: guide
      contents: guide
  page-footer:
    left: |
      <span>
        {{< var year >}} [{{< var alisp >}}]({{< var links.annuaire >}})
      </span>
      <br>
      <span>
        {{< iconify fa6-brands creative-commons >}}
        {{< iconify fa6-brands creative-commons-by >}}
        [CC BY 4.0]({{< var links.license >}})
      </span>
    center: |
      <span>
        [{{< var social.mail.text >}}]({{< var social.mail.href >}})
        [{{< var social.insta.text >}}]({{< var social.insta.href >}})
        [{{< var social.twitter.text >}}]({{< var social.twitter.href >}})
        [{{< var social.facebook.text >}}]({{< var social.facebook.href >}})
        [{{< var social.linkedin.text >}}]({{< var social.linkedin.href >}})
      </span>
    right: |
      <span>
        Site conçu avec {{< iconify fa6-brands r-project title='R' >}} et
        [{{< iconify simple-icons quarto title='Quarto' >}}](https://quarto.org/)
      </span>
      <br>
      <span>[{{< var repo.text >}}]({{< var repo.href >}})</span>
