project:
  type: website

lang: fr

filters:
  - fontawesome

format:
  hebstr-template-html: default

website:
  title: "{{< var alisp >}}"
  description: "Site officiel de l'ALISP"
  favicon: _img/sym.png
  navbar:
    background: primary
    pinned: false
    logo: _img/sym.png
    title: false
    right:
      - text: "L'asso"
        menu:
          - text: "Bureau"
            href: bureau/bureau.qmd
          - text: "Nous contacter"
            href: bureau/contact.qmd
      - text: "L'internat"
        menu:
          - text: "La santé publique à Lille"
            href: internat/lille.qmd
          - text: "Maquette du DES"
            href: internat/maquette.qmd
          - text: "Trombinoscope"
            href: internat/trombi.qmd
      - text: "Actualités"
        menu:
          - text: "Apéros-infos"
            href: evenements/apero.qmd
          - text: "Événements CLISP"
            href: evenements/clisp.qmd
      - text: Blog
        href: blog/index.qmd
      - text: "Ressources"
        href: ressources/ressources.qmd
      - text: "Aide méthodo"
        href: aide/aide.qmd
      # - text: " "
      # - text: "│"
      # - text: " "
      # - text: "{{< var links.mail.text >}}"
      #   href: "{{< var links.mail.href >}}"
      # - text: "{{< var links.insta.text >}}"
      #   href: "{{< var links.insta.href >}}"
      # - text: "{{< var links.twitter.text >}}"
      #   href: "{{< var links.twitter.href >}}"
      # - text: "{{< var links.facebook.text >}}"
      #   href: "{{< var links.facebook.href >}}"
      # - text: "{{< var links.linkedin.text >}}"
      #   href: "{{< var links.linkedin.href >}}"
      # - text: " "
      # - text: "│"
      # - text: " "
  page-footer:
    foreground: darken($primary, 20%)
    left: |
      <span>{{< fa brands creative-commons >}}&nbsp;{{< var year >}} ALISP</span><br>
      <span>{{< fa brands creative-commons >}}&nbsp;{{< fa brands creative-commons-by >}} [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>
    center: |
      [{{< var links.mail.text >}}]({{< var links.mail.href >}})&nbsp;&nbsp;&nbsp;
      [{{< var links.insta.text >}}]({{< var links.insta.href >}})&nbsp;&nbsp;&nbsp;
      [{{< var links.twitter.text >}}]({{< var links.twitter.href >}})&nbsp;&nbsp;&nbsp;
      [{{< var links.facebook.text >}}]({{< var links.facebook.href >}})&nbsp;&nbsp;&nbsp;
      [{{< var links.linkedin.text >}}]({{< var links.linkedin.href >}})
      <br>{{< var alisp >}}
    right: |
      <span>Site conçu avec {{< iconify fa6-brands r-project title='R' >}} et [{{< iconify simple-icons quarto title='https://quarto.org/' >}}](https://quarto.org/)</span><br>
      <span>[{{< var repo.text >}}]({{< var repo.href >}})</span>
