backend:
  name: github
  repo: alisp59/site-alisp
  branch: main
  base_url: https://sveltia-cms-auth.asso-isp-lille.workers.dev
  commit_messages:
    create: "content: add {{collection}} {{slug}} ({{author-login}})"
    update: "content: up {{collection}} {{slug}} ({{author-login}})"
    delete: "content: delete {{collection}} {{slug}} ({{author-login}})"
    uploadMedia: "assets: upload {{path}}"
    deleteMedia: "assets: delete {{path}}"

publish_mode: editorial_workflow

media_folder: _resources/sveltia
public_folder: /_resources/sveltia

collections:

  - name: todo
    label: TODO
    icon: checklist
    files:
      - name: todo
        label: TODO
        file: TODO.md
        extension: md
        fields:
          - name: body
            label: Contenu
            widget: markdown

  - divider: true

  - name: bureau
    label: Bureau
    icon: groups
    files:
      - name: membres
        label: Membres du bureau
        file: _resources/bureau.yml
        media_folder: _resources/images/bureau
        public_folder: /_resources/images/bureau
        fields:
          - name: bureau
            label: Membres
            widget: list
            fields:
              - name: photo
                label: Photo
                widget: image
                media_folder: _resources/images/bureau
                public_folder: /_resources/images/bureau
              - name: nom
                label: Nom
                widget: string
              - name: fonction
                label: Fonction
                widget: string
              - name: desc
                label: Description
                widget: string

  - divider: true

  - name: blog
    label: Actualités
    icon: newspaper
    label_singular: Article
    folder: blog
    path: "{{slug}}/index"
    identifier_field: slug
    media_folder: ""
    public_folder: ""
    create: true
    extension: qmd
    frontmatter_delimiter: "---"
    fields:
      - name: title
        label: Titre
        widget: string
      - name: author
        label: Auteur
        widget: string
      - name: date
        label: Date
        widget: datetime
        format: "YYYY-MM-DD"
        date_only: true
      - name: description
        label: Description
        widget: text
      - name: categories
        label: Catégories
        widget: list
      - name: image
        label: Image de couverture
        widget: image
        required: false
      - name: slug
        label: Slug
        widget: string
      - name: body
        label: Contenu
        widget: markdown

  - divider: true

  - name: guide-index
    label: "Guide > index"
    icon: description
    files:
      - name: guide-index
        label: "Guide > index"
        file: guide.qmd
        media_folder: /guide/resources
        public_folder: /guide/resources
        extension: qmd
        frontmatter_delimiter: "---"
        fields:
          - name: title
            label: Titre
            widget: string
          - name: body
            label: Contenu
            widget: markdown

  - name: guide-sections
    label: "Guide > sections"
    icon: description
    label_singular: Page
    folder: guide
    media_folder: /guide/resources
    public_folder: /guide/resources
    create: true
    extension: qmd
    frontmatter_delimiter: "---"
    fields:
      - name: title
        label: Titre
        widget: string
      - name: date
        label: Date
        widget: datetime
        format: "YYYY-MM-DD"
        date_only: true
        required: false
      - name: body
        label: Contenu
        widget: markdown
