---
title: JCISP 2026
author: ALISP
date: 2026-06-18
description: Une après-midi enrichissante !
categories:
  - JCISP
image: ''
slug: JCISP
---

💥 La Journée de communication des internes de Santé Publique des Hauts-de-France a eu lieu mardi 16 juin et a été encore une fois une belle réussite !

📅 Au programme : des présentations passionnantes sur des thèmes aussi variés que l'information médicale, la santé cardio-vasculaire, la préparation sanitaire, la pharmacovigilance et l'addictologie.

🗣️ Les discussions ont mis en lumière des approches innovantes pour améliorer la qualité des soins, renforcer la pertinence des données et optimiser la préparation sanitaire en France. Elles ont aussi rappelé l’importance fondamentale des registres de morbi-mortalité pour la recherche.

Une journée qui a confirmé, une fois de plus, la diversité des travaux menés dans le domaine de la santé publique.

❤️ Un grand merci à tous ceux qui ont contribué à faire de cet événement un moment aussi enrichissant !
