---
title: "Encadrants et structures partenaires"
---

# Procédure d’inscription pour les nouveaux arrivants

En tant qu'interne en médecine, vous devrez vous acquitter des frais universitaires et de la CVEC (Contribution Vie Étudiante et de Campus) à votre arrivée puis chaque année de votre internat. https://cvec.etudiant.gouv.fr

📞 CROUS : 09 72 59 65 65.
📧 XXXXXX

# Equipe enseignante

Inclure partie haute du trombinoscope, si l’équipe enseignante est d’accord avec cela.

# Secrétariat du DES

📧 justine.oosterlinck@chu-lille.fr

# Service de la scolarité

Le service de scolarité du 3ème cycle des études médicales est situé au 2ème étage de la faculté de médecine de Lille. Il est accessible par l’ascenseur situé devant le secrétariat du hall. C’est à cet endroit que vous pourrez déposer vos fiches d’évaluation de stage.

# Direction des Affaires Médicales et Hospitalo–Universitaires (DAMHU)

Les DAMHU sont les structures au sein de chaque centre hospitalier qui gèrent les bulletins de salaire et les dispositions financières des congés (congés annuels, maladie, maternité, paternité...). En particulier la DIRAM du CHU de Lille gère l’indemnité de transport pour les stages situés à plus de 15 kilomètres du CHU et du domicile de l’interne.

🏠DIRAM CHU Lille, 2 avenue Oscar Lambret, 59037 LILLE CEDEX.
📞 03.20.44.44.22
📧 secretariat.damhu@chu-lille.fr
📧 DAMHU@CHRU-lille.fr

Si vous êtes jeunes parents, vous pouvez contacter la DIRAM pour des renseignements sur les places dans les crèches du CHU de Lille.
Procédure congés / AM --> Num Affaires médicales

# L’Agence Régionale de Santé Hauts de France

L’agence régionale de santé gère l’agrément des lieux de stage ainsi que la répartition des stages lors de votre internat (dates, ordre de répartition). Vous pourrez trouver sur le site de l’ARS les calendriers des dates de répartitions, les listes de terrains de stage proposées (https://www.hauts-de-france.paps.sante.fr/postes-proposes), les imprimés de demande spécifiques (disponibilité, surnombre, droit au remord, etc...).

La répartition des terrains de stage a lieu sur une plateforme dématérialisée gérée par l’ARS : https://stages-internes-hdf.inea.fr/auth/connexion
Pour toute question, l’adresse mail de l’ARS Hauts de France est
📧 ARS-HDF-INTERNES@ars.sante.fr

# Le CHU de Lille

Le CHU de Lille est un acteur majeur de la santé en France, c’est le premier employeur des Hauts-de-France avec plus de 16 000 professionnels employés. Il dessert une population de près de 6 millions d'habitants. Organisé en 16 pôles couvrant toutes les spécialités médicales, le CHU de Lille est un hôpital de recours et de proximité. Il est également un moteur essentiel en matière de recherche, d’innovation scientifique, de formation et d’excellence clinique. C’est le CHU qui accueille le plus d’internes en médecine après l’AP-HP.

En étroite collaboration avec l'Université de Lille et des instituts de recherche renommés tels que l'Institut Pasteur de Lille et la Fédération régionale de recherche en santé mentale, le CHU offre un environnement d'apprentissage stimulant et interdisciplinaire. Vous pourrez aborder autant de domaines de santé publique que vous ferez de stages d’internat.
