---
title: L'offre de stages et les gardes
date: 2026-07-14
---

## **Gardes**

Les gardes sont facultatives pour les internes de santé publique sauf dans les cas suivants :

- Aux urgences de Salengro : obligatoire si stage au CHU au 1er ou 2nd semestre.
- Au centre anti-poison (CAP) : obligatoire si stage au CHU au 3ème ou 4ème semestre

## **Stages disponibles par thématique**

### **Information médicale (DIM)**

En stage dans un DIM, vous plongerez au cœur de la production et de l’analyse des données médicales. Vous découvrirez comment ces données, souvent perçues comme administratives, sont en réalité essentielles pour le pilotage des établissements, l’allocation des ressources ou l’évaluation des pratiques.

Ce stage vous fera aussi explorer des outils comme les logiciels de codage (CIM-10) ou des tableaux de bord avancés, vous comprendrez comment une bonne information médicale permet de défendre les besoins des services, d’aider les cliniciens à la production de papiers de recherche ou enfin d’orienter les politiques locales. 

- CHU : D. Theis
- GHICL : Hôpitaux de l’Université Catholique de Lille – L. Rousselet
- Lille : Centre Oscar Lambret (CLCC) – M. Cucchi
- Béthune – L. Bardoel
- Boulogne-sur-Mer – A. Lerat, J. Sicot
- Douai – B. Rossel
- Dunkerque – A. Georges
- Lens – F. Dufossez
- Roubaix – M. Djennaoui
- Valenciennes – X. Kyndt
- EPSM Lille Métropole – P. Paradis

### **Recherche clinique**

En recherche clinique, vous serez immergé dans le monde des essais thérapeutiques, des cohortes et des études interventionnelles. Votre quotidien sera de recueillir des données, analyser des résultats, contribuer à des publications et enfin valoriser vos résultats. Vous découvrirez les coulisses de la recherche et l’importance de la collaboration avec les investigateurs et les promoteurs. C’est un domaine stimulant intellectuellement où la curiosité et la méthodologie sont essentielles.

- CHU : Service archives et traitement de l’information médicale SATIM SEED – D. Theis
- EPSM : Centre collaborateur de recherche en santé mentale de l’OMS (CCOMS) – D. Sebbane
- Fédération Régionale de recherche en santé mentale (F2RSM) – A. Amad
- Centre Oscar Lambret – Unité de méthodologie et biostatistiques – MC. Le Deley

### **Hygiène** 

En milieu hospitalier, vous appliquerez et promouvrez les protocoles d’hygiène (lavage des mains, précautions standard, gestion des déchets médicaux). Vous serez aussi confrontés à des enjeux comme les infections nosocomiales ou les épidémies à l’échelle d’un hôpital. Ces stages vous montreront l’impact concret de l’hygiène sur la réduction des risques infectieux, un domaine souvent sous-estimé mais historiquement vital dans le domaine de la santé publique.

- CHU : Lutte et prévention des infections nosocomiales – Dr Loukili
- CHU : Centre Anti Poison et Toxicovigilance – P. Nisse
- CH Roubaix : Unité gestion du risque infectieux – C. Laurans
- CH Tourcoing : Unité d’Hygiène et de Lutte contre les Infections Nosocomiales – S. Alfanderi

### **Epidémiologie**

Vous analyserez des données épidémiologiques et participerez à des enquêtes de terrain. C’est ici que vous découvrirez la programmation informatique avec le data management, les modèles statistiques, la data visualisation. Ce domaine vous permettra de comprendre la dynamique des maladies dans les populations et d’aider à la prise de décision en santé publique en mettant en lumière ce qui se trame derrière des tableurs Excel massifs.

- CHU : Service de santé publique et d’épidémiologie – P. Amouyel
- Institut Pasteur de Lille – P. Amouyel

### **Politiques de santé**

Vous découvrirez comment se construisent et s’appliquent les politiques de santé à l’échelle locale et régionale. Votre rôle pourra inclure l’évaluation de programmes, la participation à des groupes de travail ou l’analyse de l’impact des réformes. Un domaine passionnant pour ceux qui veulent allier santé et politique, être médecin de santé publique en administration est un métier de traduction, de communication et de gestion de projet où vous rencontrerez des personnes formidables et passionnées.

- ARS : Direction stratégie et territoires – MM. Defebvre
- Direction Régionale du Service Médical (Villeneuve d’Ascq) : Santé publique et médecine sociale – JM. Vandendriessche

### **Prévention et promotion de la santé**

Ici, le monde de la clinique rouvre ses portes dans l’internat de santé publique, vous passerez du bureau au terrain en réalisant des campagnes de vaccination, en organisant des dépistages ou en animant des ateliers d’éducation à la santé (nutrition, addictions, santé mentale). Votre mission sera d’agir en amont des maladies en ciblant les déterminants sociaux, environnementaux et comportementaux. Vous travaillerez au sein d’une collectivité territoriale avec des acteurs variés et découvrirez comment adapter vos messages à des publics différents.

Ce stage vous montrera aussi l’importance de l’intersectorialité : la santé ne se limite pas aux hôpitaux ! Vous apprendrez à monter des projets, évaluer leur impact, et parfois à convaincre des partenaires réticents. Un domaine humain et créatif, où chaque action a un effet visible sur la santé des populations.

- Direction territoriale du Valenciennois : Pôle PMI Santé – O. Alao
- Conseil Départemental du Nord – Santé Publique / santé de l’enfant – K. Ligier, V. Leroy
- Médecine du travail et pathologies professionnelles – A. Sobaszek
- Médecine scolaire - T. Nathalie

### **Economie de la santé**

L’économie de la santé est un domaine passionnant où vous apprendrez à évaluer le rapport coût-efficacité d’interventions médicales et à analyser des modèles de financement des systèmes de santé. Ce stage sensibilise aux contraintes budgétaires en santé publique, à l’innovation et à l’optimisation des ressources pour un impact maximal sur la population. Une grande partie de la santé publique, notamment en administration, est une question d’allocation de ressources matérielles, humaines et financières.

- CHU : Direction à la recherche clinique et à l’innovation – B. Dervaux

### **Veille Sanitaire**

La veille sanitaire est un domaine où se mêlent anticipation, détection et réponse urgentes aux menaces pour la santé publique. Vous apprendrez à surveiller en temps réel les signaux d’alerte (épidémies de maladies respiratoires, toxi-infections alimentaires, signalements environnementaux…), notamment grâce aux systèmes de détection obligatoire des maladies infectieuses. Votre rôle sera véritablement celui d’un enquêteur pour endiguer des épidémies avant qu’elle ne se propage et cela à l’échelle de la région des Hauts-de-France. De plus, vous pourrez participer à la rédaction de bilans mensuels ou annuels ainsi que découvrir le monde à part entière qu’est celui de la gestion de crise, enjeu majeur de défense national, d’autant plus depuis l’épidémie de Covid-19.

- ARS : CIRE – Cellule régionale de Santé Publique France – H. Prouvost
- ARS : Veille et sécurité sanitaire – B. Defoin-Merlin

## **Procédure de choix de stage**

Préchoix – Webcerim

Nous avons une plateforme de pré choix des stages afin de nous assurer qu’il n’y ait aucun problème lors des répartitions de stage.

Phase 1 & 2 - ARS DCI Dématérialisé, amphi virtuel

La répartition des terrains de stage a lieu sur une plateforme dématérialisée gérée par l’ARS.
🌐[https://stages-internes-hdf.inea.fr/auth/connexion](https://stages-internes-hdf.inea.fr/auth/connexion)

Phase 3 - SiiMOP

La répartition des docteurs juniors se réalise sur SiiMOP et est donc annexe à celle des autres phases. Il est possible de faire ouvrir des terrains de stage, cela doit néanmoins se faire avec beaucoup d’anticipation (en moyenne un an avant le début du stage). Il est à noter qu’il faut s’inscrire à l’Ordre des Médecins au début de la phase de consolidation. 

Vous trouverez plus d’informations à ce sujet sur :

🌐[https://conseil59.ordre.medecin.fr/accueil](https://conseil59.ordre.medecin.fr/accueil)

## **Demande de dispositions particulières**

### **Mise en disponibilité**

L'interne peut être mis en disponibilité par le DG du CHU pour plusieurs motifs :

- La disponibilité pour accident ou maladie grave d'un conjoint, d'un enfant ou d'un ascendant est accordée pour un an maximum, renouvelable une fois.
- La disponibilité pour études ou recherches d'intérêt général est d'un an, renouvelable, sauf pour une thèse où elle peut aller jusqu'à trois ans. 
- Un stage de formation ou de perfectionnement peut justifier une disponibilité d'un an, renouvelable une fois. 
- La disponibilité pour convenances personnelles est possible pour un an, renouvelable une fois.

Concernant l'ancienneté requise, il faut six mois de fonctions pour les motifs d'études ou de stage et un an de fonctions pour les convenances personnelles. La procédure exige que la demande soit formulée au moins deux mois avant la date de début souhaitée. Après la période de disponibilité, la réintégration se fait au CHU de rattachement, sous réserve des postes disponibles. Pour mettre fin à la disponibilité de manière anticipée, l'interne doit prévenir l'établissement deux mois à l'avance.

### **Stage libre**

Il est prévu dans la maquette de l’internat la possibilité de réaliser un stage libre en phase socle et un en phase d’approfondissement, tout stage motivé est possible dans la mesure où vous demandez au référent du D.E.S de faire une demande d’agrément en amont et que vous vous y prenez à l’avance.

### **Stage inter-CHU**

Les demandes d’inter-CHU doivent être déposées au moins 7 mois en avance.
Les inter-CHU nécessitent un dossier solide avec un projet cohérent et mentionnant l’envie de revenir dans la région et d’y ramener les compétences acquises lors de l’inter-CHU. 

### **L’année de recherche**

Elle se déroule entre le 1er novembre et le 31 octobre. Elle peut commencer au plus tôt au début de la deuxième année du cursus et doit se terminer au plus tard un an après la validation du DES. Cette année est attribuée aux étudiants de troisième cycle des études de médecine pour l'année universitaire suivant son attribution. Les modalités d’organisation ainsi que le nombre de postes disponibles chaque année sont fixés annuellement par arrêté. L'attribution est basée sur l'évaluation de la qualité du projet de recherche soumis par l'étudiant.

### **Option EHESP**

Cette option, ouverte exclusivement aux internes de Santé Publique, prolonge l'internat d'une année. Les candidatures peuvent être soumises deux années consécutives durant la phase d'approfondissement, entre la deuxième et la troisième année d’internat ou entre la troisième année et la phase de consolidation. Les étudiants acceptés sont affectés à l'École des Hautes Études en Santé Publique (EHESP) située à Rennes pour une durée de deux semestres. L'enseignement en présentiel, d'une durée totale de trois mois, est dispensé en deux ou trois sessions. Il est possible d’effectuer un stage pour un total de neuf mois ou deux stages de trois et six mois, le lieu de stage est à votre libre choix sans restriction (en France ou à l’international) dans le domaine de l’administration de la santé publique.

### **FST - Formations spécialisées transversales**

Les FST sont ouvertes à tous les internes peu importe leur spécialité. Elles sont à réaliser lors de la phase d'approfondissement et six sont ouvertes aux internes de santé publique : 

- Addictologie
- Bioinformatique Médicale
- Hygiène-prévention de l’infection
- Médecine scolaire
- Nutrition appliquée
- Pharmacologie

Vous trouverez des informations complémentaires sur les personnes à contacter à cette adresse.

🌐[https://clisp.fr/option-et-fst/](https://clisp.fr/option-et-fst/)
