---
title: Les associations de santé publique
date: 2026-09-01
---

La vie associative est une facette importante de la santé publique. Vous serez amené à côtoyer plusieurs associations dans le monde de la santé publique à l’échelle locale, nationale et européenne. 

**Association Lilloise des Internes de Santé Publique**

C’est l’association locale des internes de santé publique. Nous représentons les internes de santé publique lors des commissions de validation de phases, maintenons une présence sur les réseaux sociaux, partageons les évènements relatifs à la santé publique dans la région et proposons une aide statistique aux internes d’autres spécialités lors de leur thèse. 

🌐 [alisp.fr](http://alisp.fr)

📧 [contact@alisp.fr](mailto:contact@alisp.fr)

**Collège de Liaison des Internes de Santé Publique**

C’est l’association nationale des internes de santé publique : 

Le Collège de Liaison des Internes de Santé Publique est une association créée en 1988. Génératrice de lien entre les internes, le CLISP œuvre à représenter les internes et faire connaître la spécialité. La formation via des séminaires, l’information et la communication en direction des internes ainsi que la réflexion à travers des groupes de travail font aussi partie intégrantes de ses missions.

🌐 [clisp.fr](http://clisp.fr)

📧 [contact@clisp.fr](mailto:contact@clisp.fr)

**Syndicat des Internes de Lille**

C’est le syndicat qui défend les droits des internes à Lille, n’hésite pas à faire un tour sur leur site internet afin de découvrir les avantages liés à l’adhésion !

🌐[internat-lille.fr](https://internat-lille.fr/)

**Euronet**

Euronet est une association internationale à but non lucratif, indépendante et non gouvernementale. Créée officiellement le 30 juin 2011, elle a pour objectif de mettre en relation les internes en santé publique à travers l'Union Européenne. Le souhait de l'association est de créer un réseau professionnel permettant de partager des informations sur les programmes de formation, de faciliter les échanges et les activités communes, ainsi que de développer un corpus de recherches scientifiques.
