---
title: Les autres activités du D.E.S de Santé Publique à Lille
date: ''
---

## **Dispensation d’enseignements**

Vous avez la possibilité d'intervenir dans les enseignements de santé publique au sein des huit Instituts de Formation en Soins Infirmiers (IFSI) de la métropole lilloise. Cet engagement implique de dispenser le cours dans l'ensemble de ces huit écoles.

Il est également envisageable, bien que facultatif, de proposer des enseignements dans d'autres IFSI de la région, à l'institut de formation des psychomotriciens de Loos ou encore auprès des orthophonistes et orthoptistes formés au CHU.

Les thématiques des cours dispensés sont les suivants :

| Semestre 1 | Semestre 2 |
| Epidémiologie analytique (2h)\n\nGrands problèmes de santé publique (2h)\n\nOrganisation et financement de la protection sociale (2h)\n\nDémarche et outils en santé publique (4h)\n\nSanté mentale (2h) | Épidémiologie descriptive (3h)\n\nOrganisation des systèmes de santé, dépenses et régulation (3h)\n\nSanté dans le monde (1h)\n\nConcept en santé publique (3h)\n\nOrganisation de la santé publique (1h)\n\nVeille sanitaire (2h) |

Des supports de cours sont déjà existants sur une plateforme dédiée (Moodle) mais peuvent être remaniés. La coordinatrice de cette activité est la Dr Victoria Gauthier. 

## **Accompagnement du Service Sanitaire**  

Il est possible de participer au déroulement du service sanitaire, cela comprend :

- 3 journées de présentations théoriques (présence facultative selon thématique)
- 2 journées d’aide méthodologique à la création de projet
- 1 journée de bilan des interventions

Pour plus d’informations sur le service sanitaire dans l’université de Lille

🌐 [https://ufr3s.univ-lille.fr/formation-initiale/service-sanitaire](https://ufr3s.univ-lille.fr/formation-initiale/service-sanitaire)

Le mail du secrétariat du service sanitaire est le suivant :

📧  [service-sanitaire-medecine@univ-lille.fr](mailto:service-sanitaire-medecine@univ-lille.fr)
